### ISSUE TITLE
len out of range

### ISSUE THREAD

**Issue by liqiangno1** [zhaojh329/rttys#44]
When rttys server runs for a while,  there is a critical error, as shown below.

```shell
2020-04-04T02:26:22Z |INFO| device.go:118 |Device '' closed 
2020-04-04T02:26:22Z |ERRO| device.go:163 |bufio: buffer full 
2020-04-04T02:26:31Z |INFO| device.go:118 |Device '' closed 
panic: runtime error: makeslice: len out of range

goroutine 48591 [running]:
main.(*Device).readLoop(0xc0001e0120)
        /home/zjh/work/rttys/device.go:196 +0x49e
created by main.listenDevice
        /home/zjh/work/rttys/device.go:256 +0x3be
```

**Comment by zhaojh329** [comment]
Please update rttys and rtty to the latest version.
