### ISSUE TITLE
BUG 数组溢出导致程序退出

### ISSUE THREAD

**Issue by umbrellary** [zhaojh329/rttys#72]
```
2021-02-03T22:04:35+08:00 |INFO| device.go:111 |Device '' closed
panic: runtime error: index out of range [0] with length 0

goroutine 468 [running]:
main.(*device).readLoop(0x40000c6090)
        /opt/gopath/src/github.com/zhaojh329/rttys/device.go:193 +0xa24
created by main.listenDevice.func1
        /opt/gopath/src/github.com/zhaojh329/rttys/device.go:263 +0x208
```

**Comment by zhaojh329** [comment]
Please use the latest version.
