### ISSUE TITLE
Building fails with code: 'ERR_OSSL_EVP_UNSUPPORTED'

### ISSUE THREAD

**Issue by InputOutputZ** [zhaojh329/rttys#96]
### rtty
* arch: x86_64
* os: centOS
* version: 8

### rttys
* arch: x86_64
* os: centOS
* version: 4

## Description
git clone git clone https://github.com/zhaojh329/rttys
cd rttys/ui
npm install
npm run build

outputs

```
> rttys-ui@0.1.0 build
> vue-cli-service build


⠸  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/root/rttys/ui/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/root/rttys/ui/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/root/rttys/ui/node_modules/webpack/lib/NormalModule.js:471:10)
    at /root/rttys/ui/node_modules/webpack/lib/NormalModule.js:503:5
    at /root/rttys/ui/node_modules/webpack/lib/NormalModule.js:358:12
    at /root/rttys/ui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/root/rttys/ui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/root/rttys/ui/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /root/rttys/ui/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/root/rttys/ui/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/root/rttys/ui/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/root/rttys/ui/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/root/rttys/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /root/rttys/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/root/rttys/ui/node_modules/loader-runner/lib/LoaderRunner.js:114
			throw e;
			^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/root/rttys/ui/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/root/rttys/ui/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/root/rttys/ui/node_modules/webpack/lib/NormalModule.js:471:10)
    at /root/rttys/ui/node_modules/webpack/lib/NormalModule.js:503:5
    at /root/rttys/ui/node_modules/webpack/lib/NormalModule.js:358:12
    at /root/rttys/ui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/root/rttys/ui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /root/rttys/ui/node_modules/loader-runner/lib/LoaderRunner.js:186:6
    at context.callback (/root/rttys/ui/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /root/rttys/ui/node_modules/cache-loader/dist/index.js:240:7
    at /root/rttys/ui/node_modules/neo-async/async.js:2830:7
    at done (/root/rttys/ui/node_modules/neo-async/async.js:2865:11)
    at /root/rttys/ui/node_modules/neo-async/async.js:2818:7
    at Array.<anonymous> (/root/rttys/ui/node_modules/cache-loader/dist/index.js:229:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

# Extra information
NPM: 8.1.3
NODE: v18.0.0-pre
OPENSSL: 3.

It seems an issue with node 18 and npm 8 and they are not supported by rttys, refer to https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported
I've ran building with npm run build NODE_OPTIONS=--openssl-legacy-provider and it did mitigate the issue with openssl yet not sure if its correct its been for ages building and yet has not been completed? Does it take long to complete building? Do you have an idea when rttys is going to support latest node and npm releases?

**Comment by InputOutputZ** [comment]
Does it take long?

**Comment by InputOutputZ** [comment]
> I tested in node v12.

Note then it doesnt work on node 18, its still in pre release state yet likely applies to already released 17.
